package com.group16.app; 

import static org.junit.jupiter.api.Assertions.assertTrue; 

import org.junit.jupiter.api.Test; 
 
public class CompilerTest {

    @Test
    public void CompilerClonesAndCompilesSuccessfully() {
        // Implement
        assertTrue(true);
    }

    @Test
    public void CompilerClonesAndCompilesUnsuccessfully() {
        // Implement
        assertTrue(false);
    }
}
